
from flask import Flask,request,render_template
from flask_paginate import Pagination,get_page_parameter
from flask_bootstrap import Bootstrap
bootstrap = Bootstrap()

# Flask学习之旅--分页功能：分别使用 flask--pagination 和分页插件 layPage
# https://article.itxueyuan.com/lXw67k

app = Flask(__name__)
bootstrap.init_app(app)

@app.route("/",methods=["GET","POST"])
def id():


    data = [
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id": 1, "stu_name": "A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
        {"stu_id":1,"stu_name":"A"},
    ]

    page = request.args.get(get_page_parameter(), type=int, default=1)
    res = data[(page - 1) * 20: page * 20]
    pagination = Pagination(page=page, total=len(data), per_page=20, css_framework='bootstrap4')
    return render_template('index.html', rows=res, pagination=pagination)




if __name__ == "__main__":
    app.run(debug=True)
